"""Render a tool selection into a Dockerfile + a content-addressed image name (docs/TOOLS.md).

PURE (stdlib only, no docker) — the ``network/squid.py`` renderer pattern, so the generated
Dockerfile is unit-testable byte-for-byte. The one IO helper, ``materialize``, writes the render to
its state-tier path so ``images.build_argv`` can point ``docker build -f`` at it.

The layer is ``FROM claude-man:<overlay>`` (the project's existing overlay stays the base stack —
the terraform overlay keeps its own recipe; tools are ADDITIVE on top of any overlay, "custom" being
simply ``base`` + a selection). Its shape mirrors the hand-written overlays: apt packages in one
``RUN`` (lists cleaned), each release artefact downloaded + **sha256-verified** in its own ``RUN``
(arch-aware via ``dpkg --print-architecture``), build-only deps purged after, the tools' ``[env]``
redirects as image ``ENV`` (overlay-scoped like the terraform overlay's — the global ``_BAKED_ENV``
is untouched), then the ``claude-man.overlay`` / ``claude-man.tools`` labels and ``USER agent``.
The hardened run profile is untouched — this changes only what is baked on the read-only rootfs
(invariant 2 holds by construction; ``image smoke`` proves it per tool).
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from .. import config
from . import library

_HEADER = "# claude-man tools layer — GENERATED by claudeman.tools.render; do not edit.\n"
_TMP = "/tmp/claude-man-tool"   # build-time scratch inside the builder (removed per RUN)


def render_dockerfile(overlay: str, tools: tuple[library.Tool, ...]) -> str:
    """The Dockerfile text baking ``tools`` (already ``library.resolve``d — closure included, library
    order) on top of ``claude-man:<overlay>``. Deterministic for the same inputs."""
    if overlay not in config.OVERLAYS:
        raise library.LibraryError(f"invalid overlay {overlay!r}: one of {config.OVERLAYS}")
    if not tools:
        raise library.LibraryError("empty tool selection — nothing to render")
    names = [t.name for t in tools]
    apt_pkgs = sorted({p for t in tools for p in t.packages})
    build_deps = sorted({p for t in tools for p in t.build_deps} - set(apt_pkgs))
    env = library.merged_env(tools)

    out = [_HEADER,
           f"# overlay: {overlay}\n# tools: {', '.join(names)}\n",
           f"FROM {config.image_tag(overlay)}\n\nUSER root\n"]
    if env:
        lines = [f"{k}={_dq(v)}" for k, v in env.items()]
        out.append("\n# Read-only-floor redirects declared by the tools' [env] (overlay-scoped ENV).\n"
                   "ENV " + " \\\n    ".join(lines) + "\n")
    if apt_pkgs or build_deps:
        pkgs = " ".join(apt_pkgs + build_deps)
        out.append("\n# apt packages"
                   + (" (+ build-only deps, purged below)" if build_deps else "") + "\n"
                   "RUN set -eux; \\\n"
                   "    apt-get update; \\\n"
                   f"    apt-get install -y --no-install-recommends {pkgs}; \\\n"
                   "    rm -rf /var/lib/apt/lists/*\n")
    for tool in tools:
        if tool.kind == "release":
            out.append(_release_run(tool))
    if build_deps:
        out.append("\n# build-only deps are not shipped\n"
                   "RUN set -eux; \\\n"
                   f"    apt-get purge -y {' '.join(build_deps)}; \\\n"
                   "    apt-get autoremove -y --purge\n")
    # A tool with `version_label` (an agent provider installed as a tool — codex) also stamps its
    # version on the layer, which is how images.image_claude_version reads it for that provider.
    versions = "".join(f' {config.LABEL_PREFIX}.{t.version_label}="{t.version}"'
                       for t in tools if t.version_label)
    out.append(f'\nLABEL {config.LABEL_PREFIX}.overlay="{overlay}" '
               f'{config.LABEL_PREFIX}.tools="{",".join(names)}"{versions}\n'
               "USER agent\n")
    return "".join(out)


def _dq(value: str) -> str:
    """Double-quote an ENV value for the Dockerfile (values are single-line by validation)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _release_run(tool: library.Tool) -> str:
    """One ``RUN`` per release tool: pick the arch's url/sha (+ tar members), download, verify the
    sha256, install by kind, clean up. ``set -eux`` + ``sha256sum -c`` make a checksum mismatch or a
    missing archive member a hard build failure."""
    dl = f"{_TMP}-{tool.name}" + (".deb" if tool.install == "deb" else ".dl")
    x = f"{_TMP}-{tool.name}.x"
    arms = []
    for arch in library.ARCHES:
        rel = tool.release[arch]
        arm = f"url='{rel.url}'; sha='{rel.sha256}'"
        if tool.install == "tar":
            arm += f"; members='{' '.join(rel.members)}'"
        arms.append(f"        {arch}) {arm} ;; \\\n")
    lines = [f"\n# --- {tool.name} {tool.version} (release/{tool.install})\n",
             "RUN set -eux; \\\n",
             '    arch="$(dpkg --print-architecture)"; \\\n',
             '    case "$arch" in \\\n',
             *arms,
             '        *) echo "unsupported arch $arch" >&2; exit 1 ;; \\\n',
             "    esac; \\\n",
             f'    curl -fsSL -o {dl} "$url"; \\\n',
             f'    echo "$sha  {dl}" | sha256sum -c -; \\\n']
    if tool.install == "binary":
        lines.append(f"    install -m 0755 {dl} /usr/local/bin/{tool.bin}; \\\n")
    elif tool.install == "tar":
        lines += [f"    mkdir -p {x}; \\\n",
                  f"    tar -xzf {dl} -C {x}; \\\n",
                  '    for m in $members; do '
                  f'install -m 0755 "{x}/$m" "/usr/local/bin/$(basename "$m")"; done; \\\n',
                  f"    rm -rf {x}; \\\n"]
    elif tool.install == "bundle":
        # The self-contained tree lands whole under /opt (its executables find their sibling libs /
        # embedded runtime relative to their real path), symlinked into /usr/local/bin by basename —
        # the same layout the AWS CLI's own `install` script produces, minus the script.
        opt = f"/opt/{tool.name}"
        extract = (f"    tar -xzf {dl} -C {x}; \\\n" if tool.archive_kind == "tar"
                   else f"    unzip -q {dl} -d {x}; \\\n")
        # tree "." = the archive root IS the tree (the Codex package: bin/ + codex-resources/ at top)
        src = f"{x}/." if tool.tree == "." else f"{x}/{tool.tree}"
        lines += [f"    mkdir -p {x}; \\\n",
                  extract,
                  f"    rm -rf {opt}; \\\n",
                  *([f"    mkdir -p {opt}; \\\n"] if tool.tree == "." else []),
                  f'    cp -a "{src}" {opt}; \\\n',
                  *(f'    test -x "{opt}/{b}"; ln -sfn "{opt}/{b}" "/usr/local/bin/{b.rsplit("/", 1)[-1]}"; \\\n'
                    for b in tool.bins),
                  f"    rm -rf {x}; \\\n"]
    else:  # deb — apt resolves its Depends; lists fetched + cleaned within the same layer
        lines += ["    apt-get update; \\\n",
                  f"    apt-get install -y --no-install-recommends {dl}; \\\n",
                  "    rm -rf /var/lib/apt/lists/*; \\\n"]
    lines.append(f"    rm -f {dl}\n")
    return "".join(lines)


def image_name(overlay: str, dockerfile: str) -> str:
    """The content-addressed image name for a rendered layer: ``<overlay>-t-<sha256[:12]>``."""
    digest = hashlib.sha256(dockerfile.encode("utf-8")).hexdigest()
    return f"{overlay}{config.TOOLS_IMAGE_SEP}{digest[:config.TOOLS_IMAGE_HASH_LEN]}"


def plan(overlay: str, selection: tuple[str, ...], *, root: Path | None = None
         ) -> tuple[str, str, tuple[library.Tool, ...]]:
    """Resolve + render a selection: ``(image_name, dockerfile, tools)``. Pure (reads the library
    only). Raises ``LibraryError`` on an unknown/invalid selection."""
    lib = library.discover(root)
    tools = library.resolve(selection, lib)
    text = render_dockerfile(overlay, tools)
    return image_name(overlay, text), text, tools


def materialize(overlay: str, selection: tuple[str, ...], *, root: Path | None = None) -> str:
    """``plan`` + write the Dockerfile to its state-tier path; returns the image name. The path is
    content-addressed, so re-materializing the same selection is idempotent (same bytes, same
    tag) and a changed selection gets a fresh dir — the old image's Dockerfile stays readable
    for `docker image` archaeology until the operator prunes it."""
    name, text, _tools = plan(overlay, selection, root=root)
    path = config.tools_dockerfile_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    return name
